name: p3l_mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  http: ^1.1.0
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.16

  font_awesome_flutter: ^10.0.0 
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.1

  carousel_slider: ^5.0.0
  retry: ^3.1.2
  flutter_secure_storage: ^9.2.2
  flutter_launcher_icons: ^0.13.1 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/iconL.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
        - asset: assets/fonts/Georgiab.ttf
          weight: 700
